name             'empty'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures empty'
long_description 'Installs/Configures empty'
version          '0.1.0'
