name             'empty'
maintainer       'john q. citizen'
maintainer_email 'john.q.citizen@test.test'
license          'All rights reserved'
description      'Installs/Configures empty'
long_description 'Installs/Configures empty'
version          '0.1.0'
