name             'empty'
maintainer       'john q. citizen'
maintainer_email 'john.q.citizen@test.test'
license          'Apache 2.0'
description      'Installs/Configures empty'
long_description 'Installs/Configures empty'
version          '0.4.0'
